### ISSUE TITLE
Does not boot

### ISSUE THREAD

**Issue by ottuzzi** [jmontleon/fedora-cubox-i_hb#10]
Hi there,

I downloaded the preconfigured image and I followed instructions to flash the SD with the image.
Everything looks right at this point: I even resized partition 3 to use full sd.
I then inserted the newly flashed SD in the cubox-i4pro and nothing happened: really nothing... does not even light up the red light in front of the cubox.
Then I flashed on the same SD SPL and u-boot.img and, at least, the front led light up... but nothing more.
I'm using the 4GB sd bundled with the cubox-i.
Do you have any idea? 

Thanks in advance
Bye
Piero

**Comment by jmontleon** [comment]
Did this get fixed? I have at times managed to download non-working images (missing u-boot, etc.). I think all uploaded images are working, but if you're still having trouble I can test the one you're trying to use that is not working.

**Comment by ottuzzi** [comment]
Hi, 

I was pretty sure I updated this issue but it looks like I only dreamed about it: I managed to get Fedora 20 up and running.. There were probably some mistakes on my side. 

Thanks for your work 
Bye 
Piero
