### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by tthtlc** [jmontleon/fedora-cubox-i_hb#11]
I wanted to compile the u-boot component, and followed the instruction in README.md (https://github.com/jmontleon/fedora-20-cubox-i_hb):

git clone https://github.com/rabeeh/u-boot-imx6.git
cd u-boot-imx6
make mx6_cubox-i_config
make
sudo dd if=SPL of=/dev/<location-of-your-fedora-20-arm-media> bs=512 seek=2
sudo dd if=u-boot.img of=/dev/<location-of-your-fedora-20-arm-media> bs=1K seek=42

For CROSS_COMPILE I set it to arm-linux-gnueabi- and executed "sh ./build-all.sh":
but got the following errors instead:

arm-linux-gnueabi/4.7/include -pipe  -DCONFIG_ARM -D__ARM__ -mthumb -mthumb-interwork -mabi=aapcs-linux -mword-relocations -march=armv7-a -Wall -Wstrict-prototypes -fno-stack-protector -Wno-format-nonliteral -Wno-format-security -fstack-usage     -o mx6_cubox-i_spl.o mx6_cubox-i_spl.c -c
mx6_cubox-i.c: In function ‘board_eth_init’:
mx6_cubox-i.c:314:6: warning: unused variable ‘reg’ [-Wunused-variable]
mx6_cubox-i.c: In function ‘board_early_init_f’:
mx6_cubox-i.c:464:36: error: ‘usb_id_pad’ undeclared (first use in this function)
mx6_cubox-i.c:464:36: note: each undeclared identifier is reported only once for each function it appears in
mx6_cubox-i.c:466:35: error: ‘usb_en_pads’ undeclared (first use in this function)
make[1]: *** [mx6_cubox-i.o] Error 1
make[1]: Leaving directory `/media/tthtlc/popo1/cubox_i4pro/u-boot-imx6/board/solidrun/mx6_cubox-i'
make: *** [board/solidrun/mx6_cubox-i/libmx6_cubox-i.o] Error 2
Error building cubox-i1 version

**Comment by jmontleon** [comment]
I am unsure on this one. I know it will compile if done on a Cubox-i or Hummingboard using Fedora 20 or 21 (but does not currently compile on Fedora 22 with GCC 5).

**Comment by jmontleon** [comment]
People should use the stock Fedora 24 images now.
