### ISSUE TITLE
Can't start GNOME using preconfigured image of Fedora 21

### ISSUE THREAD

**Issue by uidb4056** [jmontleon/fedora-cubox-i_hb#12]
Hello,
I followed the steps described to have preconfigured image of Fedora 21 and extended the partition accordingly, start the cubox without problems and do yum -y update. All of this was ok, next i installed GNOME and after start using 'init 5' the graphic environenment start but freezes the system with a message that says "A problem has occurred and the system can't recover". If I try 'startx' also gives error and not start the graphic environement.
I do something wrong?, is possible to run on a Cubox Fedora 21 with GNOME? I've missed something?
Thanks in advance for your help

Robert

**Comment by jmontleon** [comment]
Did you ever get this working? If not I can take a look at installing Fedora 21 and  gnome and seeing what happens. I know Xfce will run so I expect Gnome should too.

**Comment by uidb4056** [comment]
I've not tried anymore but I will try if you found the way to do because I'm not linux expert and your instructions will be appreciated.

**Comment by jmontleon** [comment]
People should use the stock Fedora 24 images now.
