### ISSUE TITLE
Changes on repo.maltegrosse.de

### ISSUE THREAD

**Issue by ottuzzi** [jmontleon/fedora-cubox-i_hb#15]
Hi,

   trying your script I found a problem on repo.maltegrosse.de: every file I try to get from there get a 404 answer.
It looks like redirect are not setup correctly to repo.maltegrosse.de.
So here you can find the changes that worked for me today:

wget -c http://repo.r00t.website/home:/jmontleo:/common/Fedora-${fedoraimx6release}/noarch/cubox-i_hb-uenv-${cuboxihbenvver}.fc${fedoraimx6release}.noarch.rpm
wget -c http://repo.r00t.website/home:/jmontleo:/mainline/Fedora-${fedoraimx6release}/armv7hl/kernel-${kernelversion}.fc${fedoraimx6release}.armv7hl.rpm

I also added -c to wget command to not download files every time something does not work as expected.

Thanks for your work
Bye
Piero

**Comment by jmontleon** [comment]
People should use the stock Fedora 24 images now.
