### ISSUE TITLE
Source on Repo

### ISSUE THREAD

**Issue by rickblair** [jmontleon/fedora-cubox-i_hb#16]
I am looking for the kernel source to Fedora 21 image.  Your repo (http://repo.r00t.website/home:/jmontleo:/mainline/Fedora-21/src/)  seems to only have source for kernel 4kernel-4.1.0-300.23.1.cuboxi_hb.fc21.src.rpm The kernel running in the image is 3.18.1-300.8.1  I cant seem to find that srpm anywhere.

Thanks

**Comment by jmontleon** [comment]
People should use the stock Fedora 24 images now.
