### ISSUE TITLE
Any chance of a Fedora 24 update?

### ISSUE THREAD

**Issue by kfiresmith** [jmontleon/fedora-cubox-i_hb#19]
I've got the cubox i4-pro and I'd like to dust it off and see if I can do something useful with it.  It's currently got the Fedora 22 image.

**Comment by jmontleon** [comment]
Have you tried the Fedora 24 images?

According to the support matrix it should work...
http://fedoraproject.org/wiki/Architectures/ARM/F24/Installation/Hardware_Status

Custom kernels and images may not be required anymore.

**Comment by kfiresmith** [comment]
Hrm - I haven't yet but I'll be sure to try ASAP.  I'd love to get the latest Fedora 24 bits on this small form factor :)

Thanks very much for the reply!

**Comment by jmontleon** [comment]
Sounds good. I may give it a try this weekend as well. It'd be great if it's working as well as that page suggests.

**Comment by jmontleon** [comment]
I was able to boot a Cubox-i and Hummingboard with the stock Fedora 24 images. I'm going to close this, as it appears there is little need for a custom kernel at this point.

**Comment by kfiresmith** [comment]
Hello @jmontleon  - I've been trying to sort out how to install Fedora 24 onto the cubox-i4 pro.  
The Cubox-i4 pro isn't covered well on the docs:  https://fedoraproject.org/wiki/Architectures/ARM/F23/Installation#Download_the_Disk_Image_.26_Copy_to_Media

But I've been dumping the Fedora 24 .xz image to my SD card (/dev/sdg) like so:
xzcat Fedora-Minimal-armhfp-24-1.2-sda.raw.xz | sudo dd of=/dev/sdg; sync

But here's where I get foggy:
https://fedoraproject.org/wiki/Architectures/ARM/F23/Installation#For_the_Wandboard_.28Freescale_i.MX6.29

I've attempted to adapt the wandboard instructions using the mx6cuboxi U-Boot stuff from the "root" partition of the dd'd image:

`[root@verdant /]# mount /dev/sdg3 /tmp/sdg3
[root@verdant /]# dd if=/tmp/sdg3/usr/share/uboot/mx6cuboxi/SPL of=/dev/sdg bs=1k seek=1 conv=fsync; sync
31+0 records in
31+0 records out
31744 bytes (32 kB) copied, 0.0189002 s, 1.7 MB/s
[root@verdant /]# dd if=/tmp/sdg3/usr/share/uboot/mx6cuboxi/u-boot.img of=/dev/sdg bs=1k seek=69 conv=fsync; sync
288+1 records in
288+1 records out
295312 bytes (295 kB) copied, 0.042172 s, 7.0 MB/s
[root@verdant /]# umount /tmp/sdg3
`
But doing this you don't get a boot LED on the cubox.  

Any chance you could help me figure out how to do this the right way?  Once I get it figured out I'll try to update the Fedora ARM wiki.  
Thanks!

**Comment by kfiresmith** [comment]
Additionally, here's my attempt at using the image installer script:


`

[root@verdant boards.d]# /usr/bin/fedora-arm-image-installer --image=/mnt/RAID1/ISOs/arm/Fedora-Minimal-armhfp-24-1.2-sda.raw.xz --target=mx6cuboxi --media=/dev/sdg --selinux=OFF --resizefs --norootpass

 
=====================================================
= Selected Image:                                 
= /mnt/RAID1/ISOs/arm/Fedora-Minimal-armhfp-24-1.2-sda.raw.xz
= Selected Media : /dev/sdg
= U-Boot Target : mx6cuboxi
= SELINUX = OFF
= Root Password will be removed.
= Root partition will be resized
=====================================================
 
*****************************************************
*****************************************************
******** WARNING! ALL DATA WILL BE DESTROYED ********
*****************************************************
*****************************************************
 
 Type 'YES' to proceed, anything else to exit now 
 
= Proceed? YES
= Writing: 
= /mnt/RAID1/ISOs/arm_shit/Fedora-Minimal-armhfp-24-1.2-sda.raw.xz 
= To: /dev/sdg ....
0+239692 records in
0+239692 records out
2146435072 bytes (2.1 GB) copied, 154.672 s, 13.9 MB/s
= Writing image complete!
= Resizing /dev/sdg ....
Checking that no-one is using this disk right now ... FAILED

This disk is currently in use - repartitioning is probably a bad idea.
Umount all file systems, and swapoff all swap partitions on this disk.
Use the --no-reread flag to suppress this check.

sfdisk: Use the --force flag to overrule all checks.
e2fsck 1.42.13 (17-May-2015)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
_/: 34288/78080 files (0.1% non-contiguous), 220909/312320 blocks
resize2fs 1.42.13 (17-May-2015)
The filesystem is already 312320 (4k) blocks long.  Nothing to do!

= Turning SELinux off ...
= Removing the root password.
= Writing SPL ....
31+0 records in
31+0 records out
31744 bytes (32 kB) copied, 0.0130563 s, 2.4 MB/s
= Writing u-boot.img ....
288+1 records in
288+1 records out
295312 bytes (295 kB) copied, 0.0628 s, 4.7 MB/s

= Installation Complete! Insert into the mx6cuboxi and boot.


`

**Comment by kfiresmith** [comment]
Even without the resize option it still doesn't boot - no LED.  The installer script throws no errors.
